services: 

  product_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    volumes:
      - product_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Database Migration Service
  migrate-products:
    build: 
      context: ./product_service
      dockerfile: Dockerfile
    command: ["alembic", "upgrade", "head"]
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@product_db:5432/product_db
    volumes:
      - ./product_service/app:/app/app
      - ./product_service/migration:/app/migration
    depends_on:
      product_db:
        condition: service_healthy
    restart: "no"  # Запускается только один раз

  # FastAPI Product Service
  product-api:
    build: 
      context: ./product_service
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@product_db:5432/product_db
    ports:
      - "8000:8000"
    volumes:
      - ./product_service/app:/app/app
      - ./product_service/migration:/app/migration
      - assets_images:/usr/share/nginx/html/assets/images
    depends_on:
      product_db:
        condition: service_healthy
      migrate-products:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  order_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5434:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Database Migration Service for Orders
  migrate-orders:
    build: 
      context: ./order_service
      dockerfile: Dockerfile
    command: ["alembic", "upgrade", "head"]
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@order_db:5432/order_db
    volumes:
      - ./order_service/app:/app/app
      - ./order_service/migration:/app/migration
    depends_on:
      order_db:
        condition: service_healthy
    restart: "no"  # Запускается только один раз

  # FastAPI Order Service
  order-api:
    build: 
      context: ./order_service
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@order_db:5432/order_db
    ports:
      - "8001:8000"
    volumes:
      - ./order_service/app:/app/app
      - ./order_service/migration:/app/migration
    depends_on:
      order_db:
        condition: service_healthy
      migrate-orders:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 5

  # React Frontend Application
  client-app:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    volumes:
        - assets_icons:/usr/share/nginx/html/assets/icons
        - assets_images:/usr/share/nginx/html/assets/images
    depends_on:
      product-api:
        condition: service_healthy
      order-api:
        condition: service_healthy
    environment:
      - NODE_ENV=production

  # React Frontend Application
  admin-app:
    build:
      context: ./admin-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:80"
    volumes:
        - assets_icons:/usr/share/nginx/html/assets/icons
        - assets_images:/usr/share/nginx/html/assets/images
    depends_on:
      product-api:
        condition: service_healthy
      order-api:
        condition: service_healthy
    environment:
      - NODE_ENV=production

  # Admin Database
  admin_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin_db
    ports:
      - "5435:5432"
    volumes:
      - admin_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Database Migration Service for Admin
  migrate-admin:
    build: 
      context: ./admin_service
      dockerfile: Dockerfile
    command: ["alembic", "upgrade", "head"]
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@admin_db:5432/admin_db
    volumes:
      - ./admin_service/app:/app/app
      - ./admin_service/migration:/app/migration
    depends_on:
      admin_db:
        condition: service_healthy
    restart: "no"  # Запускается только один раз

  # FastAPI Admin Service
  admin-api:
    build: 
      context: ./admin_service
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@admin_db:5432/admin_db
      PRODUCT_SERVICE_URL: http://product-api:8000
      ORDER_SERVICE_URL: http://order-api:8000
    ports:
      - "8002:8000"
    volumes:
      - ./admin_service/app:/app/app
      - ./admin_service/migration:/app/migration
    depends_on:
      admin_db:
        condition: service_healthy
      migrate-admin:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  product_pgdata:
  order_pgdata:
  admin_pgdata:
  assets_icons:
  assets_images:

networks:
  default:
    driver: bridge