from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

revision = 'e50bac094150'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer_name', sa.String(length=255), nullable=True),
    sa.Column('current_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)

    products_table = sa.table('products',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('sku', sa.String()),
        sa.column('description', sa.Text()),
        sa.column('manufacturer_name', sa.String()),
        sa.column('current_price', sa.DECIMAL()),
        sa.column('stock_quantity', sa.Integer()),
        sa.column('image_url', sa.String()),
        sa.column('attributes', postgresql.JSONB(astext_type=sa.Text())),
    )
    
    product_data = [
        {
            'id': '44a2e65e-ffd9-49ae-b266-08150ae27512',
            'name': 'Лампа-лофт',
            'sku': '241015',
            'description': 'Стильная лампа в стиле лофт станет отличным дополнением к современному интерьеру. Промышленный дизайн и качественные материалы обеспечивают долговечность и эстетическую привлекательность.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 3460,
            'stock_quantity': 125,
            'image_url': '/assets/images/Лампа-лофт_1_3460.webp',
            'attributes': {
                'material': 'Металл, сталь',
                'color': 'Черный матовый',
                'height': '~45 см (регулируемая)',
                'base_diameter': '~15 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Лофт',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'a084983c-7787-4de1-82ac-90385329ca43',
            'name': 'Лампа-лофт',
            'sku': '242015',
            'description': 'Стильная лампа в стиле лофт станет отличным дополнением к современному интерьеру. Промышленный дизайн и качественные материалы обеспечивают долговечность и эстетическую привлекательность.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 3460,
            'stock_quantity': 89,
            'image_url': '/assets/images/Лампа-лофт_2_3460.webp',
            'attributes': {
                'material': 'Металл, сталь',
                'color': 'Бронзовый',
                'height': '~45 см (регулируемая)',
                'base_diameter': '~15 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Лофт',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'f9d4159d-046b-4bcf-9198-6ee916d56aa5',
            'name': 'Лампа-лофт',
            'sku': '243015',
            'description': 'Стильная лампа в стиле лофт станет отличным дополнением к современному интерьеру. Промышленный дизайн и качественные материалы обеспечивают долговечность и эстетическую привлекательность.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 3276,
            'stock_quantity': 67,
            'image_url': '/assets/images/Лампа-лофт_3_3276.webp',
            'attributes': {
                'material': 'Металл, сталь',
                'color': 'Медный',
                'height': '~42 см (регулируемая)',
                'base_diameter': '~14 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Лофт',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': '07acb92d-ba92-4961-b818-7c6afde791a4',
            'name': 'Лампа-лофт',
            'sku': '244015',
            'description': 'Стильная лампа в стиле лофт станет отличным дополнением к современному интерьеру. Промышленный дизайн и качественные материалы обеспечивают долговечность и эстетическую привлекательность.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 3460,
            'stock_quantity': 156,
            'image_url': '/assets/images/Лампа-лофт_4_3460.webp',
            'attributes': {
                'material': 'Металл, сталь',
                'color': 'Серебристый',
                'height': '~45 см (регулируемая)',
                'base_diameter': '~15 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Лофт',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'd16fb32f-8a5c-4508-a2e4-d9c424385a85',
            'name': 'Лампа-лофт',
            'sku': '245015',
            'description': 'Стильная лампа в стиле лофт станет отличным дополнением к современному интерьеру. Промышленный дизайн и качественные материалы обеспечивают долговечность и эстетическую привлекательность.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 3460,
            'stock_quantity': 234,
            'image_url': '/assets/images/Лампа_лофт_5_3460.webp',
            'attributes': {
                'material': 'Металл, сталь',
                'color': 'Белый матовый',
                'height': '~45 см (регулируемая)',
                'base_diameter': '~15 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Лофт',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'ed52b00f-5f37-4d29-8fc4-5e0c56cd465d',
            'name': 'Лампа Junior-Chrome',
            'sku': '246015',
            'description': 'Элегантная настольная лампа "Junior-Chrome" станет незаменимым помощником в освещении вашего рабочего пространства или уголка для чтения. Благодаря своему современному дизайну и качественному хромированному покрытию, она превосходно справляется со своей задачей и служит стильным акцентом в интерьере.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 2890,
            'stock_quantity': 187,
            'image_url': '/assets/images/Лампа_хром_6_2890.webp',
            'attributes': {
                'material': 'Металл, хром',
                'color': 'Хром',
                'height': '~45 см (регулируемая)',
                'base_diameter': '~15 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Современный',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'aa1d0163-72a1-444e-a63e-a1890ebaed6a',
            'name': 'Лампа Junior-Violet',
            'sku': '247015',
            'description': 'Элегантная настольная лампа "Junior-Violet" станет незаменимым помощником в освещении вашего рабочего пространства или уголка для чтения. Благодаря своему современному дизайну и стильному фиолетовому оттенку, она превосходно справляется со своей задачей и служит ярким акцентом в интерьере.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 2890,
            'stock_quantity': 94,
            'image_url': '/assets/images/Лампа-Хром_7_2890.webp',
            'attributes': {
                'material': 'Металл, хром',
                'color': 'Фиолетовый',
                'height': '~45 см (регулируемая)',
                'base_diameter': '~15 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Современный',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'e73548c1-ebc5-4a4f-bcc3-76ca1bd42821',
            'name': 'Лампа Junior-Golden',
            'sku': '248015',
            'description': 'Элегантная настольная лампа "Junior-Golden" станет незаменимым помощником в освещении вашего рабочего пространства или уголка для чтения. Благодаря своему современному дизайну и роскошному золотистому покрытию, она превосходно справляется со своей задачей и служит премиальным акцентом в интерьере.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 3290,
            'stock_quantity': 78,
            'image_url': '/assets/images/Лампа_хром_8_3990.webp',
            'attributes': {
                'material': 'Металл, латунь',
                'color': 'Золотистый',
                'height': '~45 см (регулируемая)',
                'base_diameter': '~15 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Премиум',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'c9e5c1fe-c586-4799-bd24-a8989e3a9e9d',
            'name': 'Лампа Junior Black Matt',
            'sku': '249015',
            'description': 'Элегантная настольная лампа "Junior Black Matt" станет незаменимым помощником в освещении вашего рабочего пространства или уголка для чтения. Благодаря своему современному дизайну и стильному матовому черному покрытию, она превосходно справляется со своей задачей и служит элегантным акцентом в интерьере.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 2200,
            'stock_quantity': 145,
            'image_url': '/assets/images/Лампа_Матт_9_2200.webp',
            'attributes': {
                'material': 'Металл',
                'color': 'Черный матовый',
                'height': '~45 см (регулируемая)',
                'base_diameter': '~15 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Минимализм',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': '48e16af5-4a45-4137-a88d-63f9e3e5a1ab',
            'name': 'Лампа Junior White Art',
            'sku': '2410015',
            'description': 'Элегантная настольная лампа "Junior White Art" станет незаменимым помощником в освещении вашего рабочего пространства или уголка для чтения. Благодаря своему современному дизайну и чистому белому покрытию, она превосходно справляется со своей задачей и служит светлым акцентом в интерьере.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 2990,
            'stock_quantity': 112,
            'image_url': '/assets/images/Лампа_Белая_10_2990.webp',
            'attributes': {
                'material': 'Металл',
                'color': 'Белый',
                'height': '~45 см (регулируемая)',
                'base_diameter': '~15 см',
                'cable_length': '~1.2 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Скандинавский',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'aaec2973-04ab-48e0-b141-bac06c5bd373',
            'name': 'Лофт бра Gallo',
            'sku': '2411015',
            'description': 'Настенная лампа-бра "Gallo" сочетает в себе функциональность и стиль лофт. Идеально подходит для создания направленного освещения и атмосферного света в любом помещении. Регулируемый плафон позволяет направлять свет именно туда, где он нужен.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 9880,
            'stock_quantity': 56,
            'image_url': '/assets/images/Лампа-бра_11_9880.webp',
            'attributes': {
                'material': 'Металл, сталь',
                'color': 'Черный матовый',
                'height': '~25 см',
                'base_diameter': '~12 см (крепление)',
                'cable_length': 'Встроенная проводка',
                'lamp_type': 'Настенная',
                'mounting_type': 'Настенное крепление',
                'style': 'Лофт',
                'power': '60 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'fbeed3d8-4c61-4e5d-b63f-106a4dc2dff5',
            'name': 'Лофт бра Gallo',
            'sku': '2412015',
            'description': 'Настенная лампа-бра "Gallo" сочетает в себе функциональность и стиль лофт. Идеально подходит для создания направленного освещения и атмосферного света в любом помещении. Регулируемый плафон позволяет направлять свет именно туда, где он нужен.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 9880,
            'stock_quantity': 72,
            'image_url': '/assets/images/Лампа-бра_12_9880.webp',
            'attributes': {
                'material': 'Металл, сталь',
                'color': 'Бронзовый',
                'height': '~25 см',
                'base_diameter': '~12 см (крепление)',
                'cable_length': 'Встроенная проводка',
                'lamp_type': 'Настенная',
                'mounting_type': 'Настенное крепление',
                'style': 'Лофт',
                'power': '60 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'b3772802-a8eb-4ecd-ab63-fdbb7986c8fa',
            'name': 'Лофт бра Gallo',
            'sku': '2413015',
            'description': 'Настенная лампа-бра "Gallo" сочетает в себе функциональность и стиль лофт. Идеально подходит для создания направленного освещения и атмосферного света в любом помещении. Регулируемый плафон позволяет направлять свет именно туда, где он нужен.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 9880,
            'stock_quantity': 41,
            'image_url': '/assets/images/Лампа-бра_13_9880.webp',
            'attributes': {
                'material': 'Металл, сталь',
                'color': 'Медный',
                'height': '~25 см',
                'base_diameter': '~12 см (крепление)',
                'cable_length': 'Встроенная проводка',
                'lamp_type': 'Настенная',
                'mounting_type': 'Настенное крепление',
                'style': 'Лофт',
                'power': '60 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': '93b8682e-3746-4e6d-aa6d-081f0d51a80b',
            'name': 'Лампа-лофт Multi-Lite',
            'sku': '2414015',
            'description': 'Дизайнерская лампа "Multi-Lite" в стиле лофт с возможностью регулировки направления света. Сочетает промышленную эстетику с современной функциональностью. Идеально подходит для создания акцентного освещения в интерьере.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 13840,
            'stock_quantity': 28,
            'image_url': '/assets/images/Лампа_голубая_14_13840.webp',
            'attributes': {
                'material': 'Металл, алюминий',
                'color': 'Голубой',
                'height': '~55 см (регулируемая)',
                'base_diameter': '~18 см',
                'cable_length': '~1.5 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Дизайнерский лофт',
                'power': '60 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': '48d0428c-3616-421b-94da-04c9a011925a',
            'name': 'Лампа-лофт Multi-Lite',
            'sku': '2415015',
            'description': 'Дизайнерская лампа "Multi-Lite" в стиле лофт с возможностью регулировки направления света. Сочетает промышленную эстетику с современной функциональностью. Идеально подходит для создания акцентного освещения в интерьере.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 12470,
            'stock_quantity': 33,
            'image_url': '/assets/images/Лампа_белая_15_12470.webp',
            'attributes': {
                'material': 'Металл, алюминий',
                'color': 'Белый',
                'height': '~55 см (регулируемая)',
                'base_diameter': '~18 см',
                'cable_length': '~1.5 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Дизайнерский лофт',
                'power': '60 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': '203a3663-3ad5-4186-af17-57f14040c698',
            'name': 'Лофт бра Clam',
            'sku': '2416015',
            'description': 'Настенная лампа-бра "Clam" в форме ракушки сочетает в себе функциональность и оригинальный дизайн. Идеально подходит для создания мягкого направленного освещения и станет стильным акцентом в любом интерьере.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 10560,
            'stock_quantity': 47,
            'image_url': '/assets/images/Лампа_ракушка_белая_16_10560.webp',
            'attributes': {
                'material': 'Металл, алюминий',
                'color': 'Белый',
                'height': '~20 см',
                'base_diameter': '~15 см (крепление)',
                'cable_length': 'Встроенная проводка',
                'lamp_type': 'Настенная',
                'mounting_type': 'Настенное крепление',
                'style': 'Современный лофт',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': 'c3755c2e-614a-47a5-b59b-1890c2c82b59',
            'name': 'Лофт бра Clam',
            'sku': '2417015',
            'description': 'Настенная лампа-бра "Clam" в форме ракушки сочетает в себе функциональность и оригинальный дизайн. Идеально подходит для создания мягкого направленного освещения и станет стильным акцентом в любом интерьере.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 10560,
            'stock_quantity': 39,
            'image_url': '/assets/images/Лампа_ракушка_черная_17_10560.webp',
            'attributes': {
                'material': 'Металл, алюминий',
                'color': 'Черный',
                'height': '~20 см',
                'base_diameter': '~15 см (крепление)',
                'cable_length': 'Встроенная проводка',
                'lamp_type': 'Настенная',
                'mounting_type': 'Настенное крепление',
                'style': 'Современный лофт',
                'power': '40 Вт',
                'voltage': '220 В'
            }        },
        {
            'id': '644b1773-127b-4cb2-9754-848628756233',
            'name': 'Лампа Bombilla',
            'sku': '2418015',
            'description': 'Дизайнерская лампа "Bombilla" представляет собой современную интерпретацию классической лампочки. Элегантный минималистичный дизайн идеально впишется в любой современный интерьер, создавая мягкое и теплое освещение.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 19690,
            'stock_quantity': 15,
            'image_url': '/assets/images/Лампа_18_19690.webp',
            'attributes': {
                'material': 'Стекло, металл',
                'color': 'Прозрачный/Золотистый',
                'height': '~30 см',
                'base_diameter': '~20 см',
                'cable_length': '~1.8 м (с диммером)',
                'lamp_type': 'Подвесная/Настольная',
                'mounting_type': 'Универсальная',
                'style': 'Дизайнерский',
                'power': '25 Вт LED',
                'voltage': '220 В'
            }        },
        {
            'id': '04645360-016e-4e42-bf7f-4066f7c63a08',
            'name': 'Лампа-Dew',
            'sku': '2419015',
            'description': 'Элегантная лампа "Dew" с каплевидным дизайном создает мягкое рассеянное освещение. Современный минималистичный стиль и качественные материалы делают её идеальным выбором для создания уютной атмосферы в доме.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 5075,
            'stock_quantity': 84,
            'image_url': '/assets/images/Лампа_19_5075.webp',
            'attributes': {
                'material': 'Металл, пластик',
                'color': 'Белый',
                'height': '~35 см',
                'base_diameter': '~12 см',
                'cable_length': '~1.3 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Минимализм',
                'power': '30 Вт LED',
                'voltage': '220 В'
            }        },
        {
            'id': '5e05439d-0917-4098-8e31-e2b1afe5fd2d',
            'name': 'Лампа-Dew',
            'sku': '2420015',
            'description': 'Элегантная лампа "Dew" с каплевидным дизайном создает мягкое рассеянное освещение. Современный минималистичный стиль и качественные материалы делают её идеальным выбором для создания уютной атмосферы в доме.',
            'manufacturer_name': 'ООО "Лампочка"',
            'current_price': 5075,
            'stock_quantity': 91,
            'image_url': '/assets/images/Лампа_20_5075.webp',
            'attributes': {
                'material': 'Металл, пластик',
                'color': 'Серый',
                'height': '~35 см',
                'base_diameter': '~12 см',
                'cable_length': '~1.3 м (с выключателем на кабеле)',
                'lamp_type': 'Настольная',
                'mounting_type': 'На основании',
                'style': 'Минимализм',
                'power': '30 Вт LED',
                'voltage': '220 В'
            }
        }
    ]

    op.bulk_insert(products_table, product_data)


def downgrade() -> None:
    op.execute("DELETE FROM products")

    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')